"""Add comment field to grade and due_date to assignment

Revision ID: 44715c3aa4ab
Revises: f701bcee85ba
Create Date: 2026-03-11 21:33:27.375742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44715c3aa4ab'
down_revision = 'f701bcee85ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.Date(), nullable=True))

    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.drop_column('comment')

    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_column('due_date')

    # ### end Alembic commands ###
